<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Ti khon</name>
   <tag></tag>
   <elementGuidId>33b431d9-56db-4e18-9e67-b27bc57eec37</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ucHeader_hplMyAccount</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ctl00_ucHeader_hplMyAccount']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6087248f-5e3d-44b2-930b-15f6e9d0a800</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ucHeader_hplMyAccount</value>
      <webElementGuid>da3427e3-d7b5-4f7c-a788-8a9d7816f2c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Tài khoản</value>
      <webElementGuid>78511823-0055-4eb4-a493-c0b656c63822</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/account/account.aspx?lang=vn</value>
      <webElementGuid>b7d5acef-e421-4645-8284-2d64d8209faa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tài khoản</value>
      <webElementGuid>31868e2d-42f4-4004-9366-0912da366ae8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ucHeader_hplMyAccount&quot;)</value>
      <webElementGuid>98fcd34e-021b-42f3-9e31-5f3673323163</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ctl00_ucHeader_hplMyAccount']</value>
      <webElementGuid>8a2eb61c-8243-4ffa-9f7b-054921aa6142</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header']/div/div[4]/a</value>
      <webElementGuid>f928375d-3379-4e95-920a-323b7023b6c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Tài khoản')]</value>
      <webElementGuid>eda36eb5-9d2d-496b-a2f5-0db179f47946</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/account/account.aspx?lang=vn')]</value>
      <webElementGuid>00474131-6617-4bd5-9607-101b417dcff7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[4]/a</value>
      <webElementGuid>9b310e19-50aa-44cb-9708-ee2254006f16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ctl00_ucHeader_hplMyAccount' and @title = 'Tài khoản' and @href = '/account/account.aspx?lang=vn' and (text() = 'Tài khoản' or . = 'Tài khoản')]</value>
      <webElementGuid>55a82c90-2b76-4e1f-bdff-a05e92db1dbd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
