<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ctl00cphContentucRegistertxtLastName</name>
   <tag></tag>
   <elementGuidId>34cd3ec3-4452-4b0e-9010-7efcf453297b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_cphContent_ucRegister_txtLastName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_cphContent_ucRegister_txtLastName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ae005be9-3817-4257-a601-2e21f23ce561</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$cphContent$ucRegister$txtLastName</value>
      <webElementGuid>3961593e-3e8f-42fc-8fc6-9fb4358fb996</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>688cf774-4a65-4f51-bd19-518624d8c307</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>150</value>
      <webElementGuid>1b11240c-4cdf-4936-bb29-b315971a1b58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_cphContent_ucRegister_txtLastName</value>
      <webElementGuid>d2a491d1-e3f8-4faf-95b7-1db7c89c7d62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_cphContent_ucRegister_txtLastName&quot;)</value>
      <webElementGuid>a72b0ea9-bc5f-4170-bc5a-6ff0ebc434e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_cphContent_ucRegister_txtLastName']</value>
      <webElementGuid>b6a245d6-6355-44dc-8116-9d6954b94052</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_cphContent_ucRegister_pnlLogin']/div[4]/input</value>
      <webElementGuid>1edd3af8-e0c6-4a6f-81f6-b2ba47bb873f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>5ec2ded7-ed02-4692-91d9-475f18d3c35f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$cphContent$ucRegister$txtLastName' and @type = 'text' and @id = 'ctl00_cphContent_ucRegister_txtLastName']</value>
      <webElementGuid>ece8f2f2-1196-4ae1-a70a-e9f2c3eb9527</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
