<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ctl00cphContentucRegistertxtPhoneNumber</name>
   <tag></tag>
   <elementGuidId>f1e3293b-dc02-4d64-b171-fdd2ff8db299</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_cphContent_ucRegister_txtPhoneNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_cphContent_ucRegister_txtPhoneNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>15a0844d-95e6-47e3-b2ee-7ef379c89c21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$cphContent$ucRegister$txtPhoneNumber</value>
      <webElementGuid>adb6205d-38e9-470a-b2d8-0a8c49343ba6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>33f2e309-607a-4c0a-9420-fbe78bbdaa14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>52a4de4b-fb5d-4d6a-b7e9-da0e66376cac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_cphContent_ucRegister_txtPhoneNumber</value>
      <webElementGuid>1b3865ec-d6ed-47d5-8317-4579f543b9ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_cphContent_ucRegister_txtPhoneNumber&quot;)</value>
      <webElementGuid>d0d9d157-9b02-41e0-a76c-caba84389d99</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_cphContent_ucRegister_txtPhoneNumber']</value>
      <webElementGuid>80efaed8-2efb-445f-abcc-63bc22dbb530</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_cphContent_ucRegister_pnlLogin']/div[5]/input</value>
      <webElementGuid>887d7d08-82e6-41c8-b0e7-21375793c863</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input</value>
      <webElementGuid>ff54bfab-3959-4372-99ec-f6fcef40cea3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$cphContent$ucRegister$txtPhoneNumber' and @type = 'text' and @id = 'ctl00_cphContent_ucRegister_txtPhoneNumber']</value>
      <webElementGuid>3f8505ec-d941-47fc-81b9-d1240896762f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
