<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ctl00cphContentucLoginbtnLogin</name>
   <tag></tag>
   <elementGuidId>12c0c6a2-5ba3-4a78-ab49-5b903ba16681</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_cphContent_ucLogin_btnLogin</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_cphContent_ucLogin_btnLogin']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fe54732d-f03d-4f39-bf38-4bdaba5f8832</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>c7c998e0-b600-4841-af26-b2d3a6fa9278</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$cphContent$ucLogin$btnLogin</value>
      <webElementGuid>e0bfb5cf-2e93-4bb0-9548-378590de06b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>ĐĂNG NHẬP</value>
      <webElementGuid>09152acc-9df8-4ef7-803c-90360e50c5c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_cphContent_ucLogin_btnLogin</value>
      <webElementGuid>121d64fd-c4a4-45ef-b07c-8ca61e7506be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>login</value>
      <webElementGuid>8d3064d5-0d76-45ff-b36b-b1653581405e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_cphContent_ucLogin_btnLogin&quot;)</value>
      <webElementGuid>28cc3d8e-54b9-4b19-995e-2057985a4ab7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_cphContent_ucLogin_btnLogin']</value>
      <webElementGuid>a6379958-ed0a-4176-b0a3-17295d28f289</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_cphContent_ucLogin_pnlLogin']/div[5]/input</value>
      <webElementGuid>5f0a91cf-1e4c-4b99-9bed-df927a4c6ddb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[5]/input</value>
      <webElementGuid>4f0a792a-35e3-47e0-80a0-01a6fb3a08f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'ctl00$cphContent$ucLogin$btnLogin' and @id = 'ctl00_cphContent_ucLogin_btnLogin']</value>
      <webElementGuid>658347d5-ba88-41dd-be13-f0a91bbc5755</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
