<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ctl00cphContentucRegistertxtAddress</name>
   <tag></tag>
   <elementGuidId>4044ef4b-8c65-4a4f-92a6-ad13720cacb2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_cphContent_ucRegister_txtAddress</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_cphContent_ucRegister_txtAddress']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8c110243-0ed3-4c24-b0ea-494abaae764f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$cphContent$ucRegister$txtAddress</value>
      <webElementGuid>fb0295ec-e531-4025-a4fc-9bd77ab026ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9856091e-0a1a-4520-b20c-07c0d2631de9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>250</value>
      <webElementGuid>fd2e957d-0755-43cd-a9b5-c7c6aa300048</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_cphContent_ucRegister_txtAddress</value>
      <webElementGuid>515e0caf-cffa-458d-870e-d18518085df5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_cphContent_ucRegister_txtAddress&quot;)</value>
      <webElementGuid>fdf2e0d9-9724-44f3-acf4-881cec4ed239</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_cphContent_ucRegister_txtAddress']</value>
      <webElementGuid>f9838594-c45b-4562-be37-4afb315048f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_cphContent_ucRegister_pnlLogin']/div[6]/input</value>
      <webElementGuid>4979b88e-1fad-4416-ac2a-9b1f44d4c31a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/input</value>
      <webElementGuid>4dd339c5-5df5-4490-9000-8f98830d3af8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$cphContent$ucRegister$txtAddress' and @type = 'text' and @id = 'ctl00_cphContent_ucRegister_txtAddress']</value>
      <webElementGuid>ca61497d-4b6d-488c-9b10-5d6c5377b2a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
