<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ctl00cphContentucRegistertxtEmail</name>
   <tag></tag>
   <elementGuidId>c003a8ed-1444-411a-8827-af607cf850dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_cphContent_ucRegister_txtEmail</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_cphContent_ucRegister_txtEmail']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>04c03eb1-d61a-42cf-8a3d-8b734fadafce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$cphContent$ucRegister$txtEmail</value>
      <webElementGuid>8eec5798-b11d-44e5-b72b-b6aa953115e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1a5b5cea-8880-4154-bcd0-1d3877201ae4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>febfa08f-b307-4cfa-be7e-586faa71823e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_cphContent_ucRegister_txtEmail</value>
      <webElementGuid>373bd0da-463c-4669-8086-631e61f46e43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_cphContent_ucRegister_txtEmail&quot;)</value>
      <webElementGuid>ccdab8b9-793f-4dbe-a764-a24c1b86f714</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_cphContent_ucRegister_txtEmail']</value>
      <webElementGuid>be23692f-67e3-4b7b-9323-b156c7304b8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_cphContent_ucRegister_pnlLogin']/div/input</value>
      <webElementGuid>9a081eaa-862c-4539-b9ec-a4ff7babc7bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/input</value>
      <webElementGuid>cd6167cf-cec8-475d-96a1-424ff3245d95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$cphContent$ucRegister$txtEmail' and @type = 'text' and @id = 'ctl00_cphContent_ucRegister_txtEmail']</value>
      <webElementGuid>df580575-8cba-4b44-a768-7c60c9bed18d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
