<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Sign in</name>
   <tag></tag>
   <elementGuidId>40ad3d9c-3397-4309-8ba6-aae809617a79</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.sign-in</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ctl00_ucHeader_pnlSignin']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>935cb445-cce3-443f-bab0-35cd83ac111a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/account/account.aspx?lang=vn</value>
      <webElementGuid>0908ce06-abb4-4b3e-827e-99c6e8ab059b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Sign in</value>
      <webElementGuid>fcb5adf7-e38e-46b4-b290-2aa1de948104</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sign-in</value>
      <webElementGuid>1059fc1e-6efd-4f7d-a2f8-acba9ad51e8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign in</value>
      <webElementGuid>da5f3594-e8b9-4478-9520-0bcc5e31d269</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ucHeader_pnlSignin&quot;)/a[@class=&quot;sign-in&quot;]</value>
      <webElementGuid>553da8b5-a7c4-479f-b2a8-ce2a3215b283</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_ucHeader_pnlSignin']/a</value>
      <webElementGuid>583649ad-ded0-47b7-9917-5b7c63b11045</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Sign in')]</value>
      <webElementGuid>3961b723-1c93-4446-a25d-bc63a3eaf92f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/account/account.aspx?lang=vn')])[2]</value>
      <webElementGuid>91b8deb6-df4d-48ae-b0aa-58afac6216ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/a</value>
      <webElementGuid>1bf718c4-3690-4156-b9ca-11ea8464b10d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/account/account.aspx?lang=vn' and @title = 'Sign in' and (text() = 'Sign in' or . = 'Sign in')]</value>
      <webElementGuid>5a7ed7d1-c71f-4e00-ac63-5d2fc190938f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
